[profile.dev]
opt-level = 3
debug = false
lto = true

[profile.release]
opt-level = 3
lto = true

[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2018"

[dependencies]
num-complex = "0.2.3"
image = "0.22.2"
num_cpus = "1.10.1"
rayon = "1.2.0"
